# Numpy

In [3]:
import numpy as np

## 1) Array Creation

### 1.1 From function

In [1]:
lst = list(range(1,100,5))
print(lst)

[1, 6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86, 91, 96]


In [4]:
arr = np.arange(1,100,5)
print(arr)
print(type(arr))

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
<class 'numpy.ndarray'>


### 1.2 From list

In [6]:
l1 = [1,2,3,4]
arr1 = np.array(l1)
print(l1)
print(arr1)

[1, 2, 3, 4]
[1 2 3 4]


In [13]:
list2d = [[1,2],[3,4],[5,6]]
arr2d = np.array(list2d)
print(list2d)
print(arr2d)
print(type(arr2d[0]))

[[1, 2], [3, 4], [5, 6]]
[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [10]:
#Numpy array should be homogeneous
list2d = [[1],[3,4],[5,6,7]]
arr2d = np.array(list2d)
print(list2d)
print(arr2d)
type(arr2d[0])

[[1], [3, 4], [5, 6, 7]]
[list([1]) list([3, 4]) list([5, 6, 7])]


list

In [16]:
#Numpy array should be homogeneous
list2d = [[1,2],[3,4],['5','6']]
arr2d = np.array(list2d)
print(list2d)
print(arr2d)
type(arr2d[0])

[[1, 2], [3, 4], ['5', '6']]
[['1' '2']
 ['3' '4']
 ['5' '6']]


numpy.ndarray

### 1.3 Character array

In [18]:
charar = np.chararray((3, 3))
charar[:] = 'h'
print(charar)

[[b'h' b'h' b'h']
 [b'h' b'h' b'h']
 [b'h' b'h' b'h']]


In [20]:
charar2 = np.chararray((3, 3),itemsize=5)
charar2[:] = 'hello'
charar2[:] = 'hello world'
print(charar2)

[[b'hello' b'hello' b'hello']
 [b'hello' b'hello' b'hello']
 [b'hello' b'hello' b'hello']]


### 1.4 Some others arrays

In [21]:
#Zero matrix
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
#Zero matrix
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [27]:
#[0,1] in uniform distribution
np.random.rand(4)

array([0.98760499, 0.99596404, 0.01763298, 0.28191321])

In [28]:
#in normal distribution
np.random.randn(4)

array([-1.67318704, -0.38476716,  0.43851861, -1.20337329])

In [32]:
# random integers
np.random.randint(1,50,8)

array([21, 28,  7, 34,  7, 36, 33, 15])

## 2) Operations

### 2.1 Addition, Subtraction, Multiplication, Division

In [33]:
arr = np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [98]:
#print(arr + 5)
arr1 = np.arange(10,20,1)
#shape must be same
arr2 = np.arange(10,20,1)
print(arr1)
print(arr2)
print(arr1+arr2)

[10 11 12 13 14 15 16 17 18 19]
[10 11 12 13 14 15 16 17 18 19]
[20 22 24 26 28 30 32 34 36 38]


In [37]:
# In list concatenation occurs
l1 = [1,2,3]
l2 = [5,6,7]
l3 = [4]
print(l1+l2+l3)

[1, 2, 3, 5, 6, 7, 4]


In [58]:
# for inf check
arr = np.arange(1,20,2)
#arr = np.arange(0,19,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19]


In [59]:
arr2 = np.arange(0,100,10)
print(arr2)

[ 0 10 20 30 40 50 60 70 80 90]


In [60]:
print(arr*arr2)

[   0   30  100  210  360  550  780 1050 1360 1710]


In [61]:
print(arr2/arr)

[0.         3.33333333 4.         4.28571429 4.44444444 4.54545455
 4.61538462 4.66666667 4.70588235 4.73684211]


In [64]:
#division with zero handled but should be avoided
print(arr/arr2)


[       inf 0.3        0.25       0.23333333 0.225      0.22
 0.21666667 0.21428571 0.2125     0.21111111]


c:\users\ranger\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


In [67]:
s = arr/arr2
#s[0]==float('inf')
s[0]==np.inf
#s[0]==np.nan
#np.isnan(s[0])

c:\users\ranger\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


True

### 2.2 dtype shape reshape

In [89]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [90]:
print(arr1.dtype)
print(np.result_type(arr1))

int32
int32


In [91]:
print(arr2.dtype)
print(np.result_type(arr2))

int32
int32


In [86]:
#explicitly give type
arrf = np.array([1.5,2,3,4,5], dtype=np.float64)
print(arrf)
print(arrf.dtype)

[1.5 2.  3.  4.  5. ]
float64


In [81]:
lst = ['1','2','3']
lst2 = [[1,2,3],[5,6,7]]
lst+lst2+[1,2]

['1', '2', '3', [1, 2, 3], [5, 6, 7], 1, 2]

In [92]:
print(arr1)

[1 2 3 4 5]


In [93]:
arrnew = np.append(arr1, 'hi')
print(arrnew)
print(arrnew.dtype)

['1' '2' '3' '4' '5' 'hi']
<U11


In [101]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [102]:
print(arr1.shape)
#print(arr2.shape)

(5,)


In [103]:
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [106]:
arr3 = arr2.reshape(4,3)
print(arr3)
#print(arr3.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 2.3 other numpy operation

In [107]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [108]:
print(arr1.max())

5


In [112]:
print(arr2)
print(arr2.max())
print(arr2[0].max())
print(arr2[1].max())

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
6
12


In [113]:
arr2.min()

1

In [120]:
print(arr2.argmin())
#Cannot be used to access element but only know the position
print(arr2.argmax())
#arr1[arr1.argmax()]
#arr1[arr1.argmin()]
arr2[arr2.argmax()]

0
11


IndexError: index 11 is out of bounds for axis 0 with size 2

In [125]:
#arr2[1][5]

# Way1
#i,j = np.unravel_index(arr2.argmax(), arr2.shape)
#print(i,j)
#arr2[i][j]

# Way2
#arr2[np.where(arr2==arr2.max())]
#print(np.where(arr2==arr2.max()))

array([12])

In [126]:
print(arr1)

[1 2 3 4 5]


In [127]:
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [128]:
print(np.log(arr1))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [129]:
print(np.exp(arr1))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [130]:
print(np.sin(arr1))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [131]:
print(np.cos(arr1))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [132]:
print(np.tan(arr1))

[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


### 2.4 indexing

In [133]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([    [1,2,3,4,5,6], [7,8,9,10,11,12], [0,2,4,3,1,5] , [9,8,7,6,5,4]  ])

In [134]:
print(arr1[0:2])

[1 2]


In [136]:
arr1[0:2] = 0
print(arr1)

[0 0 3 4 5]


In [137]:
arr1 = np.array([1,2,3,4,5])
arr = arr1.copy()
arr[:] = 0
print(arr)
print(arr1)

[0 0 0 0 0]
[1 2 3 4 5]


In [138]:
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 0  2  4  3  1  5]
 [ 9  8  7  6  5  4]]


In [139]:
# row,col
print(arr2[2][2])

4


In [140]:
print(arr2[2])

[0 2 4 3 1 5]


In [141]:
print(arr2[2:5])

[[0 2 4 3 1 5]
 [9 8 7 6 5 4]]


In [142]:
print(arr2[2][1:3])

[2 4]


In [143]:
print(arr1)

[1 2 3 4 5]


In [144]:
print(arr1>3)

[False False False  True  True]


In [145]:
print(arr1[arr1>3])

[4 5]


In [146]:
print(np.where(arr1>3))

(array([3, 4], dtype=int64),)


In [147]:
arr1[np.where(arr1>3)]

array([4, 5])

In [149]:
arr[arr1>3]

array([0, 0])